language: go
go:
- 1.3
- 1.4
- 1.5
- 1.6
os:
- linux
install:
- go get code.google.com/p/go.tools/cmd/cover || go get golang.org/x/tools/cmd/cover
- go get github.com/hailiang/goveralls
- make install
script:
- cd algoliasearch
- go test -v -covermode=count -coverprofile=profile.cov
after_script:
- export PATH=$PATH:$HOME/gopath/bin/
- cd algoliasearch
- goveralls -coverprofile=profile.cov -service=travis-ci
env:
  global:
  - secure: "d2aDJoNrk31w2JUZoD++vKOLM4fzEqMYVArgDB37ab6tECMAYtIJ/+UgPbUFc/QdGhXuGZzKMKYFjp2q5ip4YIlK7CIuSNgoU8pFJEC5EcmdVQ2I5Zgksf+5Fb7OulG0IB/Gn7N7BdPrrOO5S/nO/GQsPKep0ARENb99CsZkQkQ="
  - secure: "RHnww0V58Ifk6PrGvvnj+5F11FlCwoDry3s6A9Ag9p97iw2hS/L1iI8SHNP2QngSV9Hi1gtGREgisOZe0y/xUpVP+LXSDiBgSwGLa7FiEaM1jHX0mGiJaDXiaTl2TBlCA/BKxUUQtd0pduqqb3YrAjaM6YJvXWilRogSsxbleoY="
